AWSTemplateFormatVersion: 2010-09-09

Description: An AWS Certificate Manager certificate for the provided domains in this Region

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
    - Parameters:
      - DomainName
      - SubjectAlternativeNames
      - ValidationDomainName

Parameters:
  DomainName:
    Type: String
    Default: "*.mycompany.com"
    MinLength: 1
    MaxLength: 253
    AllowedPattern: ^(\*\.)?(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])$
    Description: Fully qualified domain name (FQDN), such as www.mycompany.com, of the site that you want to secure with an ACM Certificate. Use an asterisk (*) to create a wildcard certificate that protects several sites in the same domain. For example, *.mycompany.com protects www.mycompany.com, site.mycompany.com, and images.mycompany.com.
    ConstraintDescription: must be a valid FQDN, between 1 and 253 characters.
  SubjectAlternativeNames:
    Type: CommaDelimitedList
    Default: "*.mycompany.net, *.mycompany.org"
    Description: FQDNs to be included in the Subject Alternative Name extension of the ACM certificate. For example, you can add www.mycompany.net to a certificate for the www.mycompany.com domain name so that users can reach your site by using either name.
    ConstraintDescription: must be a list of valid FQDNs.  The total number of FQDNs should be one more than the total number of commas. Also, each member FQDN is space trimmed.
  ValidationDomainName:
    Type: String
    Default: "*.mycompany.com"
    MinLength: 1
    MaxLength: 253
    AllowedPattern: ^(\*\.)?(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])$
    Description: The domain name that you want ACM to use to send you validation emails. This must be the same as the DomainName value or a superdomain of the DomainName value. For example, if you request a certificate for testing.example.com, you can specify example.com for this value.
    ConstraintDescription: must be a valid domain, between 1 and 253 characters.

Resources:
  # ACM Certificate for this region
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref DomainName
      DomainValidationOptions:
      -
        DomainName: !Ref DomainName
        ValidationDomain: !Ref ValidationDomainName
      SubjectAlternativeNames: !Ref SubjectAlternativeNames
        
Outputs:
  Certificate:
    Value: !Ref Certificate
    Description: ARN of the new AWS Certificate Manager certificate.