AWSTemplateFormatVersion: 2010-09-09

Description: An Active Directory (or Samba 4 Active Directory Compatible Server) replicated across two Availability Zones.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    -
      Label:
        default: Subnet Configuration
      Parameters:
      - NetworkStackName
      - Subnet1CidrBlock
      - Subnet2CidrBlock
    -
      Label:
        default: Active Directory Configuration
      Parameters:
      - Type
      - Size
      - DirectoryName
      - NetbiosName
      - AdminPassword

Parameters:
  Type:
    Type: String
    Default: SimpleAD
    AllowedValues:
    - SimpleAD
    - MicrosoftAD
    Description: The type of Directory server to create.  Choose "MicrosoftAD" for a standard Microsoft Active Directory server.  For a smaller/cheaper alternative, choose "SimpleAD" for a Samba 4 Active Directory Compatible Server.
  Size:
    Type: String
    Default: Small
    AllowedValues:
    - Small
    - Large
    Description: The size of Directory server to create.  This parameter is only valid for SimpleAD type Directories; it is ignored for MicrosoftAD type Directories.  A "Large" Directory is recommended for organizations with 100 or more active users.
  NetworkStackName:
    Type: String
    Default: MainVPC
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Description: Name of an active CloudFormation stack that contains the networking resources needed to create a bastion host in its own public subnet.
    ConstraintDescription: must contain only alphanumeric characters and/or hyphens, and start with a letter
  Subnet1CidrBlock:
    Type: String
    Default: 10.0.130.0/28
    Description: CIDR block of the first new subnet.  Two subnets will be allocated by this stack, allowing AWS Directory Service to isolate/replicate directory objects across two Availability Zones.  Each subnet will contain a directory server and a DNS server.  Block size must be between a /16 netmask and a /28 netmask.
    AllowedPattern: ^\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}(\/\d{1,2})?$
    ConstraintDescription: must be a valid CIDR blocks (e.g., 10.20.114.0/24)
  Subnet2CidrBlock:
    Type: String
    Default: 10.0.130.16/28
    Description: CIDR block of the first new subnet.  Two subnets will be allocated by this stack, allowing AWS Directory Service to isolate/replicate directory objects across two Availability Zones.  Each subnet will contain a directory server and a DNS server.  Block size must be between a /16 netmask and a /28 netmask.
    AllowedPattern: ^\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}(\/\d{1,2})?$
    ConstraintDescription: must be a valid CIDR blocks (e.g., 10.20.114.0/24)

  DirectoryName:
    Type: String
    Default: corp.example.com
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^([a-zA-Z0-9]+[\\.-])+([a-zA-Z0-9])+$
    Description: A fully qualified domain name (for example, corp.example.com). This name will resolve inside your VPC only. It does not need to be publicly resolvable.
    ConstraintDescription: must contain only alphanumeric characters and/or hyphens, and start with a letter
  NetbiosName:
    Type: String
    Default: CORP
    MinLength: 1
    MaxLength: 15
    AllowedPattern: ^[^\\/:*?\"\<\>|.]+[^\\/:*?\"<>|]*$
    Description: The NetBIOS name for your domain. This value must be 15 characters or less.
    ConstraintDescription: must contain only alphanumeric characters and/or hyphens, and start with a letter
  AdminPassword:
    Type: String
    NoEcho: true
    AllowedPattern: (?=^.{8,64}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9\s])(?=.*[a-z])|(?=.*[^A-Za-z0-9\s])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9\s]))^.*
    Description: The password for the default directory administrative user.
    ConstraintDescription: "must have an 8-character minimum with at least one character having at least three of these attributes: lowercase, uppercase, numeric, and special characters."

Conditions:
  CreateSimpleAD: !Equals [ !Ref Type, "SimpleAD" ]
  CreateMicrosoftAD: !Equals [ !Ref Type, "MicrosoftAD" ]

Resources:
  # Network ACL for the new public subnet(s)
  PubACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !ImportValue MainVPC
  InEphemeraAcl:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PubACL
      RuleNumber: 130
      Egress: false
      RuleAction: allow
      Protocol: 6
      PortRange: { From: 1024, To: 65535 }
      CidrBlock: 0.0.0.0/0
  InIcmpAcl:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PubACL
      RuleNumber: 140
      Egress: false
      RuleAction: allow
      Protocol: 1
      Icmp: { Code: -1, Type: -1 }
      CidrBlock: 0.0.0.0/0
  OutIcmpAcl:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PubACL
      RuleNumber: 140
      Egress: true
      RuleAction: allow
      Protocol: 1
      Icmp: { Code: -1, Type: -1 }
      CidrBlock: 0.0.0.0/0

  # Define the two subnets in different Availability Zones
  DirectorySubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue MainVPC
      AvailabilityZone: !Select [ 0, !GetAZs ]
      CidrBlock: !Ref Subnet1CidrBlock
      MapPublicIpOnLaunch: true
  RTAssoc1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !ImportValue PublicRouteTable
      SubnetId: !Ref DirectorySubnet1
  ACLAssoc1:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref PubACL
      SubnetId: !Ref DirectorySubnet1

  DirectorySubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue MainVPC
      AvailabilityZone: !Select [ 1, !GetAZs ]
      CidrBlock: !Ref Subnet2CidrBlock
      MapPublicIpOnLaunch: true
  RTAssoc2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !ImportValue PublicRouteTable
      SubnetId: !Ref DirectorySubnet2
  ACLAssoc2:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref PubACL
      SubnetId: !Ref DirectorySubnet2

  # Active Directory
  SimpleAD:
    Type: AWS::DirectoryService::SimpleAD
    Condition: CreateSimpleAD
    Properties:
      Name: !Ref DirectoryName
      Description: A Samba 4 Active Directory Compatible Server for the organization.
      CreateAlias: true
      ShortName: !Ref NetbiosName
      Password: !Ref AdminPassword
      Size: !Ref Size
      EnableSso: true  # Single sign-on for computers connected to the AD (like WorkSpaces)
      VpcSettings:
        VpcId: !ImportValue MainVPC
        SubnetIds:
        - !Ref DirectorySubnet1
        - !Ref DirectorySubnet2
  MicrosoftAD:
    Type: AWS::DirectoryService::MicrosoftAD
    Condition: CreateMicrosoftAD
    Properties:
      Name: !Ref DirectoryName
      CreateAlias: true
      ShortName: !Ref NetbiosName
      Password: !Ref AdminPassword
      EnableSso: false  # Single sign-on for computers connected to the AD (like WorkSpaces)
      VpcSettings:
        VpcId: !ImportValue MainVPC
        SubnetIds:
        - !Ref DirectorySubnet1
        - !Ref DirectorySubnet2

Outputs:
  ActiveDirectory:
    Value: !Ref SimpleAD
    Condition: CreateSimpleAD
    Description: The ID of the new Active Directory
  ActiveDirectory:
    Value: !Ref MicrosoftAD
    Condition: CreateMicrosoftAD
    Description: The ID of the new Active Directory