AWSTemplateFormatVersion: 2010-09-09

Description: General IAM principals for an AWS account

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
    - Parameters:
      - OrganizationPrefix
      - AdminPassword

Parameters:
  OrganizationPrefix:
    Type: String
    Default: "mycompany"
    AllowedPattern: ^[\w+=,.@-]*$
    Description: An optional prefix to append to all IAM principals (e.g., "mycompany")
    ConstraintDescription: "must be a string of upper and lowercase alphanumeric characters with no spaces, and any of the following characters: =,.@-.  Note that group names are not distinguished by case."
  AdminPassword:
    Type: String
    NoEcho: true
    Description: The password for the administrator IAM user.
    ConstraintDescription: must conform to this AWS account's password policy, if any.

Resources:
  # IAM Groups and Policicies
  AdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ["-", [ !Ref OrganizationPrefix, admins ] ]
      Path: /admins/
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess
  PowerUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ["-", [ !Ref OrganizationPrefix, power-users ] ]
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/PowerUserAccess
      Path: /power-users/
  PowerUserMinusPortalGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ["-", [ !Ref OrganizationPrefix, power-users-minus-portal ] ]
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/PowerUserAccess
      Path: /power-users-minus-portal/
  DenyPortalAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: Prevents IAM principals from managing the AWS portal for this account.
      Path: /deny-portal-access/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Deny
          Action: "aws-portal:*"
          Resource: "*"
      Groups: [ !Ref PowerUserMinusPortalGroup ]
  ReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ["-", [ !Ref OrganizationPrefix, read-only-users ] ]
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/ReadOnlyAccess
      Path: /read-only-users/
      
  # IAM Users and Policies
  AdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join ["-", [ !Ref OrganizationPrefix, admin ] ]
      Path: /admins/admin/
      Groups: [ !Ref AdminGroup ]
      LoginProfile:
        Password: !Ref AdminPassword
        PasswordResetRequired: false
        
Outputs:
  AdminUser:
    Value: !Ref AdminUser
    Description: UserName of the new administrative user.