AWSTemplateFormatVersion: '2010-09-09'

Description: VPC with an Internet Gateway

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
        - CidrBlock

Parameters:
  CidrBlock:
    Type: String
    Default: 10.0.128.0/24
    AllowedPattern: ^\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}(\/\d{1,2})?$
    Description: The CIDR block for the new VPC.
    ConstraintDescription: must be a valid CIDR block (e.g., 52.20.114.0/24)

Resources:
  MainVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  MainIGW:
    Type: AWS::EC2::InternetGateway
  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MainIGW
      VpcId: !Ref MainVPC

Outputs:
  MainVPC:
    Value: !Ref MainVPC
    Description: The ID of the new Virtual Private Cloud
    Export:
      Name: MainVPC
  MainIGW:
    Value: !Ref MainIGW
    Description: The ID of the new Internet Gateway
    Export:
      Name: MainIGW
