AWSTemplateFormatVersion: 2010-09-09

Description: An S3 bucket for Lambda functions, and IAM principals for managing Lambda in the AWS account

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
    - Parameters:
      - OrganizationPrefix
      - LogBucketName

Parameters:
  OrganizationPrefix:
    Type: String
    Default: mycompany
    AllowedPattern: ^[\w+=,.@-]*$
    Description: An optional prefix to append to all bucket names and IAM principals (e.g., "mycompany")
    ConstraintDescription: "must be a string of upper and lowercase alphanumeric characters with no spaces, and any of the following characters: =,.@-.  Note that group names are not distinguished by case."
  LogBucketName:
    Type: String
    Default: lambda
    AllowedPattern: ^[a-z0-9.-]+$
    Description: The name of the bucket to which the Lambda-function S3 bucket will store logs.
    ConstraintDescription: must contain only lowercase letters, numbers, periods (.), and dashes (-).

Resources:
  # S3 bucket for Lambda functions
  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: !Join [ "-", [ !Ref OrganizationPrefix, !Ref "AWS::Region", lambda ] ]
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucketName
        LogFilePrefix: lambda/
          
  # IAM Groups and Policies
  LambdaAdmins:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ["-", [ !Ref OrganizationPrefix, lambda-admins ] ]
      Path: /lambda-admins/
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSLambdaFullAccess
  LambdaReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ["-", [ !Ref OrganizationPrefix, lambda-read-only ] ]
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess
      Path: /lambda-read-only/
  LambdaBucketAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: Allows Lambda users to work with the Lambda-functions S3 bucket.
      Path: /lambda-bucket-access/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        -
          Effect: Deny
          Action: "s3:*"
          NotResource:
          - !Join ["", [ "arn:aws:s3:::", !Ref OrganizationPrefix, "-", !Ref "AWS::Region", "-", lambda ] ]
          - !Join ["", [ "arn:aws:s3:::", !Ref OrganizationPrefix, "-", !Ref "AWS::Region", "-", lambda, "/*" ] ]
      Groups:
      - !Ref LambdaAdmins
      - !Ref LambdaReadOnlyGroup
        
Outputs:
  LambdaBucket:
    Value: !Ref LambdaBucket
    Description: Name of the new Lambda logs bucket.
  LambdaAdminGroup:
    Value: !Ref LambdaAdmins
    Description: Name of the new Lambda admin group.
  LambdaReadOnlyGroup:
    Value: !Ref LambdaReadOnlyGroup
    Description: Name of the new Lambda read-only group.