AWSTemplateFormatVersion: '2010-09-09'

Description: VPC with an Internet Gateway

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
        - CidrBlock
        - FlowLogTrafficType

Parameters:
  CidrBlock:
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: ^\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}(\/\d{1,2})?$
    Description: The CIDR block for the new VPC.
    ConstraintDescription: must be a valid CIDR block (e.g., 52.20.114.0/24)
  FlowLogTrafficType:
    Type: String
    Default: ALL
    AllowedValues: [ ALL, ACCEPT, REJECT, NONE ]
    Description: The type of traffic into/out of this VPC to log.  You can log all traffic, or only traffic that was accepted or rejected.  If you choose NONE, then no flow log will be created.
  FlowLogRoleArn:
    Type: String
    Default: arn:aws:iam::ACCOUNT-ID:role/flow-log-role
    Description: The ARN of a role that will allow the flow logs service to publish flow logs to CloudWatch Logs.  If you chose NONE for FlowLogTrafficType, then this value will be ignored.

Conditions:
  CreateFlowLog: !Not [ !Equals [ !Ref FlowLogTrafficType, NONE ] ]
    
Resources:
  MainVPC:
    # The main VPC for this region
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      
  # Internet Gateway association
  MainIGW:
    Type: AWS::EC2::InternetGateway
  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MainIGW
      VpcId: !Ref MainVPC
      
  # Route Table association
  PubRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVPC
  InternetRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MainIGW
      RouteTableId: !Ref PubRT
      
  # Flow Log association
  VpcFlowLog:
    Type: AWS::EC2::FlowLog
    Condition: CreateFlowLog
    Properties:
      DeliverLogsPermissionArn : !Ref FlowLogRoleArn
      LogGroupName : !Join [ "-", [ !Ref "AWS::StackName", flow-log ] ]
      ResourceId : !Ref MainVPC
      ResourceType : VPC
      TrafficType : !Ref FlowLogTrafficType

Outputs:
  MainVPC:
    Value: !Ref MainVPC
    Description: The ID of the new Virtual Private Cloud
    Export:
      Name: MainVPC
  PublicRouteTable:
    Value: !Ref PubRT
    Description: The ID of the new Internet Gateway
    Export:
      Name: PublicRouteTable
