AWSTemplateFormatVersion: '2010-09-09'

Description: VPC with an Internet Gateway

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Parameters:
        - CidrBlock
        - FlowLogTrafficType

Parameters:
  CidrBlock:
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: ^\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}(\/\d{1,2})?$
    Description: The CIDR block for the new VPC.  Block size must be between a /16 netmask and a /28 netmask.
    ConstraintDescription: must be a valid CIDR block (e.g., 10.20.114.0/24)
  FlowLogTrafficType:
    Type: String
    Default: ALL
    AllowedValues: [ ALL, ACCEPT, REJECT, NONE ]
    Description: The type of traffic into/out of this VPC to log.  You can log all traffic, or only traffic that was accepted or rejected.  If you choose NONE, then no flow log will be created.

Conditions:
  CreateFlowLog: !Not [ !Equals [ !Ref FlowLogTrafficType, NONE ] ]

Resources:
  MainVPC:
    # The main VPC for this region
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  MainVpcIpv6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref MainVPC

  # Internet Gateway association
  MainIGW:
    Type: AWS::EC2::InternetGateway
  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MainIGW
      VpcId: !Ref MainVPC

  # Route Table association
  PubRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVPC
  InternetRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MainIGW
      RouteTableId: !Ref PubRT

  # Flow Log association
  VpcFlowLog:
    Type: AWS::EC2::FlowLog
    Condition: CreateFlowLog
    Properties:
      DeliverLogsPermissionArn : !GetAtt FlowLogRole.Arn
      LogGroupName : !Sub ${AWS::StackName}-vpc-flow-logs
      ResourceId : !Ref MainVPC
      ResourceType : VPC
      TrafficType : !Ref FlowLogTrafficType
  FlowLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${AWS::StackName}-vpc-flow-logs
      RetentionInDays: 60
  FlowLogRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-vpc-flow-log-role
      Path: !Sub /flow-log-roles/${AWS::StackName}/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - # Allow the VPC service to assume this role
            Sid: AssumeRole
            Effect: Allow
            Principal: { Service: vpc-flow-logs.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
      - PolicyName: FlowLogAccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - # Allows this role to create log streams in the new log group, and write log events to them
            Sid: WriteFlowLogEvents
            Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            Resource: !GetAtt FlowLogGroup.Arn

Outputs:
  MainVPC:
    Value: !Ref MainVPC
    Description: ID of the new Virtual Private Cloud
    Export: { Name: MainVPC }
  PublicRouteTable:
    Value: !Ref PubRT
    Description: ID of the new Internet Gateway
    Export: { Name: PublicRouteTable }
