AWSTemplateFormatVersion: 2010-09-09

Description: Returns AMIs and other values that are specific to the requested AWS Region.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    -
      Parameters:
      - LambdaS3Bucket
      - S3Key

Parameters:
  LambdaS3Bucket:
    Type: String
    Default: mycompany-region-lambda
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[0-9A-Za-z\.\-_]*(?<!\.)$
    Description: Name of the S3 bucket where the deployment package is stored. This bucket must reside in the same AWS region where you are creating the Lambda function.
    ConstraintDescription: must contain only alphanumeric characters and/or one or more of the symbols .-_?<!
  S3Key:
    Type: String
    Default: region-lookup.zip
    MinLength: 1
    MaxLength: 1024
    ConstraintDescription: must be a valid S3 key of length 1-1024.
    Description: The name (S3 key) of the deployment package for this function, inside the Lambda S3 bucket.

Resources:
  RegionLookupFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: RegionLookup
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref S3Key
      Handler: region-lookup.handler
      Description: This Lambda function returns returns AMIs and other values that are specific to the requested AWS Region
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs4.3
      Timeout: 30
      MemorySize: 128   # MB, must be a multiple of 64 <= 1536, default is 128
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: region-lookup-lambda-role
      Path: /region-lookup-lambda-role/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - # Allow the Lambda service to assume this role
          Sid: AssumeRole
          Effect: Allow
          Principal: { Service: lambda.amazonaws.com }
          Action: sts:AssumeRole
      Policies:
      - PolicyName: region-lookup-lambda-role
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - # Allow sending logs to a log group
            Sid: SendLogs
            Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - # Allow describing EC2 images, so we can find the latest AMI image IDs!
            Sid: LambdaDescribeImages
            Effect: Allow
            Action: ec2:DescribeImages
            Resource: "*"
Outputs:
  RegionLookupFunction:
    Value: !Ref RegionLookupFunction
    Description: FunctionName of the new AWS Region Lookup Lambda function.
